Use specific rake version to fix `Gem::InstallError`
12.2.1 is the last version which supports ruby 1.9.

```
  1) Error:
AcceptanceTest#test_binstub_upgrade_with_old_binstub:
RuntimeError: command failed
$ bundle check || bundle update --retry=2
--- stdout ---
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from http://rubygems.org/...............
Fetching gem metadata from http://rubygems.org/..
Resolving dependencies....
Fetching rake 12.3.1
Installing rake 12.3.1
Gem::InstallError: rake requires Ruby version >= 2.0.0.
An error occurred while installing rake (12.3.1), and Bundler cannot continue.
Make sure that `gem install rake -v '12.3.1' --source 'http://rubygems.org/'`
succeeds before bundling.
```

https://travis-ci.org/mtsmfm/spring-debug/jobs/404541780